
# https://github.com/libp2p/js-libp2p-webrtc-star
version: '3.7'
networks:
  default:
services:
  star-signal: 
    container_name: 'star-signal' 
    image: sinlov/libp2p-webrtc-star-service:0.21.2-alpine # https://hub.docker.com/r/sinlov/libp2p-webrtc-star-service/tags?page=1&ordering=last_updated
    ports:
      - '9090:9090'
    environment:
      - STAR_SIGNAL_HOST=0.0.0.0
    restart: always # on-failure:3 or unless-stopped always default noc