version: '3'
services:
  app:
    image: ipfsshipyard/rb-pinning-service-api:v0.1.0
    ports:
      - "5000:5000"
    environment:
      - RAILS_ENV=development
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=development
      - DATABASE_HOST=database.service.pinning.internal
      - REDIS_URL=redis://redis.service.pinning.internal
      - IPFS_URL=ipfs.service.pinning.internal
    networks:
      - internal
    depends_on:
      - database.service.pinning.internal
      - redis.service.pinning.internal
      - ipfs.service.pinning.internal

  database.service.pinning.internal:
    image: postgres:9.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=development

  redis.service.pinning.internal:
    image: redis:6.0-alpine
    networks:
      - internal

  ipfs.service.pinning.internal:
    image: ipfs/go-ipfs:latest
    ports: 
      - 4001:4001 
      - 4001:4001/udp 
      - 127.0.0.1:8080:8080 
      - 127.0.0.1:5001:5001
    networks:
      - internal
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./container-init.d:/container-init.d/
      - ./data/ipfs:/ipfsdata
  
  star-signal: 
    container_name: 'star-signal' 
    image: sinlov/libp2p-webrtc-star-service:0.21.2-alpine # https://hub.docker.com/r/sinlov/libp2p-webrtc-star-service/tags?page=1&ordering=last_updated
    ports:
      - '9090:9090'
    environment:
      - STAR_SIGNAL_HOST=0.0.0.0
    restart: always # on-failure:3 or unless-stopped always default noc

volumes:
  pg_data:

networks:
  internal:
    driver: bridge